# See: https://github.com/mkdocs/mkdocs/blob/master/docs/user-guide/configuration.md
site_name: PassCave
site_description: PassCave is password management system.
site_author: purnendukar
repo_url: https://github.com/purnendukar/PassCave

nav:
- Introduction: index.md
- API:
  - Overview: api/0-overview.md
  - Authentication: api/1-auth.md
  - Secret Manager: api/2-credential.md
  - Plan: api/3-plan.md
  - Secret Group: api/4-secret-group.md
  - Bank Secret: api/5-bank-secret.md
  - Web App Secret : api/6-web-app-secret.md
  - Secret Note: api/6-secret-note.md
  # - Errors: api/errors.md
# - Technical Specs:
#   - Server Config: backend/server_config.md
#   - Coding Rules: backend/coding_rules.md
  # - Database Schema: backend/database-schema.svg
- Releases:
  - Changelog: releases.md

theme:
  name: 'material'
  features:
    - tabs
    - instant
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate 
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode


plugins:
  - git-revision-date-localized


copyright: 'Copyright © 2021 - 2022 Purnendu Kar'

# directory to output HTML build
site_dir: _docs_html

# Determines if a broken link to a page within the documentation is considered
# a warning or an error (link to a page not listed in the pages setting). Set to
# true to halt processing when a broken link is found, false prints a warning.
strict: true

# Determines the address used when running mkdocs serve.
# Set it to 8001, so that it doesn't conflict with django's 8000 port
dev_addr: '127.0.0.1:8001'

markdown_extensions:
  - admonition
  - markdown.extensions.meta
  - markdown.extensions.admonition
  - markdown.extensions.smarty
  - markdown.extensions.sane_lists
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.mark
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - markdown_include.include:
      base_path: docs
